require: rubocop-rspec
inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  targetRubyVersion: 2.3
  Exclude:
   - 'db/**/*'
   - 'bin/*'
   - 'config/environments/*'
   - 'config/application.rb'
   - 'config/initializers/*'
   - 'config/spring.rb'
   - 'lib/tasks/*'
   - 'vendor/**/*'
   - 'path/ruby'

LineLength:
  Max: 150

Lint/AssignmentInCondition:
  Enabled: false