default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: portfolio1_development
  pool: 5
  username: <%= ENV["MYSQL_USER_NAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>

development:
  <<: *default
  database: portfolio1_development

test:
  <<: *default
  database: portfolio1_test
  # username: root
  # password:

production:
  <<: *default
  host: <%= ENV["AWS_DATABASE_ENDPOINT"] %>
  database: <%= ENV["AWS_CATABASE"] %>
  username: <%= ENV["AWS_USER_NAME"] %>
  password: <%= ENV["AWS_DATABASE_PASSWORD"] %>