# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c259191673e202b8ca88dae9da0dea865048ebc6eaad04ba5090c9c9a172e99ca5046fa63eb751fef830cd67d11b483d8233fd7fcbe77dffa026ae04a5d1fa07

test:
  secret_key_base: 3bbc41134e677dbbbb80d793a1cbf1965df0f76f242ba1abaefe8624d1adfe018558d4c1cef552408bc2de5498cb4367982a954596a76a4bc84f8e4c6b7247eb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
